### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [jagrosh/WheresTheParty#6]
Having an issue with building this project. 

`[ERROR] Failed to execute goal on project Hackweek: Could not resolve dependencies for project com.jagrosh:Hackweek:jar:0.2: Failed to collect dependencies at com.github.DV8FromTheWorld:JDA:jar:experimental~lazy-loading-SNAPSHOT: Failed to read artifact descriptor for com.github.DV8FromTheWorld:JDA:jar:experimental~lazy-loading-SNAPSHOT: Could not transfer artifact com.github.DV8FromTheWorld:JDA:pom:experimental~lazy-loading-SNAPSHOT from/to central (http://jcenter.bintray.com): Authorization failed for http://jcenter.bintray.com/com/github/DV8FromTheWorld/JDA/experimental~lazy-loading-SNAPSHOT/JDA-experimental~lazy-loading-SNAPSHOT.pom 403 Forbidden`

**Comment by jagrosh** [comment]
[Latest commit](https://github.com/jagrosh/WheresTheParty/commit/962d4af92ef576322d79872bea8ef5fe012dbc1f) should fix this, it was an outdated dependency from before some new features were merged into the main jda branch.
